// Generated by AMillasseau


#include "Scene.h"

namespace render {

	/// @brief Full constructor of the Scene class.
    Scene::Scene(state::Game* game,sf::Transform transform){
		this->enableInput = true;
		//Store game attribute
		this->game = game;
		this->transform = transform;

       	//Creation and initialisation of the background texture
    	this->background_texture =sf::Texture();
    	(this->background_texture).loadFromFile("./resources/img/background.png");

    	//Creation and initialisation of the background sprite
    	this->background=sf::Sprite();
    	(this->background).setTexture(this->background_texture);

    	//Set Starting Window
    	this->current_window = MAIN_WINDOW;

		PlayerRenderer* pRenderer;
		Button* button;

		//Get Players
		std::vector<state::Player*> players = game->getPlayers();

		//Generate PlayerRenderer for MAIN_WINDOW
		for (int i = 0; i<(int) players.size();i++){
			pRenderer = new PlayerRenderer(players[i],generatePlayerTransform(transform,MAIN_WINDOW,i),MAIN_WINDOW);
    		this->player_renderer.push_back(pRenderer);
		}

		//Generate PlayerRenderer for DRAFTING_WINDOW
		for (int i = 0; i<(int) players.size();i++){
    		pRenderer = new PlayerRenderer(players[i],generatePlayerTransform(transform,DRAFTING_WINDOW,i),DRAFTING_WINDOW);
			this->player_renderer.push_back(pRenderer);
		}
		
		//Generate PlayerRenderer for PLAYER_INFO
		pRenderer = new PlayerRenderer(game->getPlayers()[0],transform,PLAYER_INFO);
		this->player_renderer.push_back(pRenderer);

		//Generate PlayerRenderer for PLANIFICATION_WINDOW
		pRenderer = new PlayerRenderer(game->getPlayers()[0],transform,PLANIFICATION_WINDOW);
		this->player_renderer.push_back(pRenderer);

		//Generate DraftingHandRenederer
		this->drafting_hand_renderer = new DraftingHandRenderer((game->getPlayers())[0],sf::Transform(transform).translate(0.f,900.f));

		//Generate GameRenderer
		this->game_renderer = new GameRenderer(game,transform);

		//Generate Buttons for MAIN_WINDOW only if the Player isn't an AI
		if(this->enableInput){
			button = new Button({1650.f,480.f},{100.f,100.f},"MATERIAL",sf::Color(100,100,100),NULL);
			button->setVisible(true);
			this->btnMain.push_back(button);
			button = new Button({1770.f,480.f},{100.f,100.f},"ENERGY",sf::Color::Black,NULL);
			button->setVisible(true);
			this->btnMain.push_back(button);
			button = new Button({1650.f,600.f},{100.f,100.f},"SCIENCE",sf::Color::Green,NULL);
			button->setVisible(true);
			this->btnMain.push_back(button);
			button = new Button({1770.f,600.f},{100.f,100.f},"GOLD",sf::Color::Yellow,NULL);
			button->setVisible(true);
			this->btnMain.push_back(button);
			button = new Button({1650.f,720.f},{100.f,100.f},"EXPLORATION",sf::Color::Blue,NULL);
			button->setVisible(true);
			this->btnMain.push_back(button);
			button = new Button({1770.f,720.f},{100.f,100.f},"KRYSTALIUM",sf::Color::Red,NULL);
			button->setVisible(true);
			this->btnMain.push_back(button);
			button = new Button({1650.f,840.f},{100.f,100.f},"COLONEL",sf::Color::Red,NULL);
			button->setVisible(true);
			this->btnMain.push_back(button);
			button = new Button({1770.f,840.f},{100.f,100.f},"FINANCIER",sf::Color::Cyan,NULL);
			button->setVisible(true);
			this->btnMain.push_back(button);

			button = new Button({1650.f,960.f},{220.f,100.f},"END PROD",sf::Color::White,NULL);
			button->setVisible(true);
			this->btnMain.push_back(button);
			button = new Button({50.f,960.f},{220.f,100.f},"SAVE GAME",sf::Color::White,NULL);
			button->setVisible(true);
			this->btnMain.push_back(button);

			for(int i = 1; i<(int) game->getPlayers().size();i++){
				button = new Button({300.f,60.f*i},{200.f,50.f},"Switch to:"+game->getPlayers()[i]->getName(),sf::Color(215,47,215),NULL);
				button->setVisible(true);
				this->btnMain.push_back(button);
			}

			button = new Button({20.f,780.f},{220.f,100.f},"KEEP",sf::Color(215,47,215),NULL);
			button->setVisible(true);
			this->btnPlan.push_back(button);
			button = new Button({260.f,780.f},{220.f,100.f},"DISCARD",sf::Color(215,47,215),NULL);
			button->setVisible(true);
			this->btnPlan.push_back(button);
			button = new Button({1680.f,780.f},{220.f,100.f},"DISCARD ALL",sf::Color(215,47,215),NULL);
			button->setVisible(true);
			this->btnPlan.push_back(button);

			button = new Button({1600.f,940.f},{220.f,100.f},"CONFIRM",sf::Color(215,47,215),NULL);
			button->setVisible(true);
			this->btnDraft.push_back(button);

			for(int i = 0; i<(int) game->getPlayers().size();i++){
				button = new Button({550.f+220.f*i,50.f},{200.f,50.f},"Switch to:"+game->getPlayers()[i]->getName(),sf::Color(215,47,215),NULL);
				button->setVisible(true);
				this->btnFull.push_back(button);
			}
		}

	}

    /// @brief Full destructor of the Scene class.
    Scene::~Scene (){

    }

	/// @brief Setter for current_window
	/// @param window new window
	void Scene::changeWindow(Window window){
		this->current_window = window;
	}

	/// @brief Getter for current_window
	/// @return value of current_window
	Window Scene::getWindow(){
		return (this->current_window);
	}

	/// @brief Setter for player displayed in PLAYER_INFO
	/// @param index index of Player to display in players
	void Scene::changePlayerInfoPlayer(int index){
		//Get Player to be display
		state::Player* player = game->getPlayers()[index];

		//Get Transform
		sf::Transform t = this->player_renderer[4]->getPos();

		//Create Renderer
		PlayerRenderer* pRenderer = new PlayerRenderer(player,t,PLAYER_INFO);

		//Link the renderer (Observer) to its Observable (Game & player) 
		player->addObserver(pRenderer);
		game->addObserver(pRenderer);

		//TODO Destroy previous Renderer?

		//Update the just created Renderer with the current state of the game
		pRenderer->update();
		//Put the new Renderer in its place
		this->player_renderer[4] = pRenderer;
	}

	/// @brief Generator for Transform for PlayerRenderer
	/// @param transform Base Transform of window
	/// @param window Window where the Renderer will be display
	/// @param indice index of the player to display
	/// @return Transform for the PlayerRenderer
	sf::Transform Scene::generatePlayerTransform(sf::Transform transform, Window window, int indice){
		if (window == MAIN_WINDOW){
			if (indice == 0){
				return sf::Transform(transform).translate(525.f,780.f);
			}
			else {
				return sf::Transform(transform).translate(525.f,0.f);
				//TODO See for indice>2
			}
		}
		if (window == DRAFTING_WINDOW){
			if (indice == 0){
				return sf::Transform(transform).translate(0.f,720.f);
			}
			else {
				return sf::Transform(transform).translate(0.f,(indice-1)*180.f);
			}
		if (window == PLANIFICATION_WINDOW){
			return sf::Transform(transform);
		}
		}
	return sf::Transform(transform);
	}

	/// @brief update the Scene with the current state of the game
	void Scene::update(){
		btnMain[0]->setText("MATERIAL\n("+std::to_string(this->game->getPlayers()[0]->getCurrentResources()[state::MATERIAL])+")");
		btnMain[1]->setText("ENERGY\n("+std::to_string(this->game->getPlayers()[0]->getCurrentResources()[state::ENERGY])+")");
		btnMain[2]->setText("SCIENCE\n("+std::to_string(this->game->getPlayers()[0]->getCurrentResources()[state::SCIENCE])+")");
		btnMain[3]->setText("GOLD\n("+std::to_string(this->game->getPlayers()[0]->getCurrentResources()[state::GOLD])+")");
		btnMain[4]->setText("EXPLORATION\n("+std::to_string(this->game->getPlayers()[0]->getCurrentResources()[state::EXPLORATION])+")");
		btnMain[5]->setText("KRYSTALLIUM\n("+std::to_string(this->game->getPlayers()[0]->getCurrentResources()[state::KRYSTALLIUM])+")");
		btnMain[6]->setText("COLONEL\n("+std::to_string(this->game->getPlayers()[0]->getCurrentResources()[state::COLONEL])+")");
		btnMain[7]->setText("FINANCIER\n("+std::to_string(this->game->getPlayers()[0]->getCurrentResources()[state::FINANCIER])+")");
		
	}

	void Scene::draw(sf::RenderWindow& window){
		
		switch (this->current_window){
			case MAIN_WINDOW:
				window.draw(this->background,this->transform);		//Background
				//Display GameRenderer
				this->game_renderer->draw(window);			
				
				//Display players
				for (int i=0; i < 2; i++){
					this->player_renderer[i]->draw(window);
				}
				for (Button* btn: btnMain){
					btn->draw(window);
				}

				break;
			case DRAFTING_WINDOW:
				//Display players
				for (int i=2; i < 4; i++){
					this->player_renderer[i]->draw(window);
				}
				//Display Drafting Hand
				this->drafting_hand_renderer->draw(window);

				for (Button* btn: btnDraft){
					btn->draw(window);
				}
				break;
			case PLAYER_INFO:
				//Display Player
				this->player_renderer[4]->draw(window);

				for (Button* btn: btnFull){
					btn->draw(window);
				}
				break;
			case PLANIFICATION_WINDOW:
				window.draw(this->background,this->transform);
				//Display Drafted Hand
				this->player_renderer[5]->draw(window);

				for (Button* btn: btnPlan){
					btn->draw(window);
				}
				break;
			default:
				break;
			}

	}

	void Scene::setupObserver(state::Observable* observable){
		observable->addObserver(this->game_renderer);
		for(PlayerRenderer* pRenderer: player_renderer){
			observable->addObserver(pRenderer);
		}
		observable->addObserver(this->drafting_hand_renderer);
		observable->addObserver(this);
	}
};
