// Generated by AMillasseau


#include "Scene.h"

namespace render2 {

    Scene::Scene (){
    	this->background_texture =sf::Texture();
    	//(this->background_texture).loadFromFile("file");
    	this->background=sf::Sprite();
    	(this->background).setTexture(this->background_texture);
    	/*TODO PlayerRenderer*/
    }

    Scene::~Scene (){

    }

    void Scene::displayDraftCard (){

    }

    void Scene::draw (){
    	(this->window).draw((this->background));
    	(this->own_player_renderer).draw(&(this->window));
    	for (PlayerRenderer p : (this->other_player_renderer)) {
    		p.draw(&(this->window));
    	}
    }


};
